# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build_sbom

on:
  push:
    branches: [ "main" , "actiontest"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" , "actiontest"]
  schedule:
    - cron: '25 17 * * 0'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status 
    name: Build
    runs-on: "ubuntu-18.04"
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/ocastel/log4j-shell-poc:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/ocastel/log4j-shell-poc:${{ github.sha }}'
          format: 'github'
          template: '@/contrib/sarif.tpl'
          output: 'dependency-results.sbom.json'
          github-pat: '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'
